name: LOTP - Docker

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "docker/**"

permissions:
  contents: read

jobs:
  probe:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: docker build -f Dockerfile .
        working-directory: docker
        continue-on-error: true
