name: LOTP - Terraform

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - ".github/workflows/terraform.yml"
      - "terraform/**"

permissions:
  contents: read

jobs:
  probe:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: terraform plan
        working-directory: terraform
        continue-on-error: true
